// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jqvpjprtpuwxvcbfcgjg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpxdnBqcHJ0cHV3eHZjYmZjZ2pnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4ODA2ODgsImV4cCI6MjA3MTQ1NjY4OH0.4waWnf6xU0G69AdnrwNuN15WshNEKLfpEM6Rzqr00AQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});